### ISSUE TITLE
魔改

### ISSUE THREAD

**Issue by BernardXiong** [zhaohengbo/rt-boot#1]
RT 🥇 

确实Makefile还是不可避免的，看来后续RT-Thread必须加入对Makefile的支持 💯 欢迎对RT-Thread提供更多的建议

**Comment by zhaohengbo** [comment]
居然是大神前来捧场，您的rt thread是众多rtos中最棒的，您也一直是我从小崇拜的偶像，没有您的rt thread也就没有rt-boot，感谢您的付出！

**Comment by zhaohengbo** [comment]
另外建议的话我在想console输出方式是不是可以分情况判断，系统设计一个默认console设备，一个内核console设备，每个线程也有自己的一个console设备，rt_kprintf输出时，判断如果当前处于内核状态（中断nest大于0或者当前线程=0）使用内核console输出，如果线程没有指定特殊console则使用默认console输出，否则使用线程console输出，我觉得这样便于shell在不同的接口（比如多个串口或者是多个telnet接入）上启动不同的副本。这个想法和finsh的全局变量线程私有化的想法我打算先在rt-boot上试一试，因为它需要这种启动多shell的能力

**Comment by BernardXiong** [comment]
每个任务自己的printf，stdio是可以的。但其他的可能就不见得了，或者说，实现的资源占用代价太大了

**Comment by zhaohengbo** [comment]
原来还有这重考虑，学习了
