### ISSUE TITLE
编译失败，提示bash: ./tools/mips-relocs文件不存在

### ISSUE THREAD

**Issue by elecfunwb** [zhaohengbo/rt-boot#2]
编译失败，提示bash: ./tools/mips-relocs文件不存在
> bash: ./tools/mips-relocs: No such file or directory

尝试去掉RT-BOOT/Makefile 262行SUBDIRS = #tools里的注释，改为SUBDIRS = tools，重新编译提示
> mips-openwrt-linux-musl-gcc: error: environment.c: No such file or directory

查看RT-BOOT/tools/Makefile 133行
> environment.c:
		@rm -f environment.c
		ln -s ../common/lib/environment.c environment.c

tools下的environment.c文件链接到../common/lib/environment.c，但实际../common下无lib文件夹，应为libs，而且也没有environment.c文件。

**Comment by zhaohengbo** [comment]
这个文件需要在uboot2018.11rc3下独立编译[它的tools文件夹下也有个相似的文件，直接覆盖然后用ap143_config编译]，编译完拷贝回rt-boot目录下
