### ISSUE TITLE
can't build based on debian 8.1

### ISSUE THREAD

**Issue by baidxi** [zhaohengbo/rt-boot#3]
a - webclient_file.o
Unable to find .rel section
Makefile:299: recipe for target 'u-boot' failed
make[1]: *** [u-boot] Error 234
Makefile:252: recipe for target 'tp-link_tl-wr810n_v2' failed
make: *** [tp-link_tl-wr810n_v2] Error 2

**Comment by baidxi** [comment]
gcc version 4.8

**Comment by zhaohengbo** [comment]
建议使用buildroot或者openwrt生成工具链，第三方工具链可能会不支持一些特性

**Comment by zhaohengbo** [comment]
我使用的是openwrt生成的工具链

**Comment by zhaohengbo** [comment]
测试过buildroot生成的arm工具链
