### ISSUE TITLE
mkimage.c not found tinf.h

### ISSUE THREAD

**Issue by baidxi** [zhaohengbo/rt-boot#4]
compiler mkimage.c not found tinf.h

**Comment by zhaohengbo** [comment]
这个文件直接从uboot_mod里面编译好了提取出来用吧，这个是一样的，因为rt-boot是全新写的Bootloader所以很多uboot里的头文件是没有的

**Comment by baidxi** [comment]
编译出来了，但是，不能启动。

**Comment by zhaohengbo** [comment]
注意spl的编译，最好使用uboot_mod并根据帖子做修改，最好验证能启动uboot_mod

**Comment by zhaohengbo** [comment]
mkimage最好使用uboot_mod的版本
